FROM rustembedded/cross:armv7-unknown-linux-gnueabihf-0.2.1 as context

RUN dpkg --add-architecture armhf && \
    apt-get update && \
    apt-get install -y libssl-dev:armhf libdbus-1-dev:armhf

ENV PKG_CONFIG_PATH=/usr/lib/arm-linux-gnueabihf/pkgconfig
