#!/bin/sh

set -e

if [ "$1" = "configure" ] ; then
  touch /etc/mijia-homie/sensor-names.toml
  adduser --system --home /etc/mijia-homie mijia-homie
  adduser mijia-homie bluetooth
  chown mijia-homie /etc/mijia-homie/mijia-homie.toml
fi

#DEBHELPER#
