[target.armv7-unknown-linux-gnueabihf]
objcopy = {path = "arm-linux-gnueabihf-objcopy" }
strip = {path = "arm-linux-gnueabihf-strip" }

[target.arm-unknown-linux-gnueabi]
objcopy = {path = "arm-linux-gnueabi-objcopy" }
strip = {path = "arm-linux-gnueabi-strip" }
